title: Learning New Technologies
author: Matt Rarick
email: peperarick.com
description: > # this means to ignore newlines until "baseurl:"
  This is where we will share our experiences as we take a deep dive 
  into learning new technologies. We hope that this blog will be informative 
  and entertaining. Feedback is welcome and appreciated.
  
# social links
twitter_username: your-twitter-handle
github_username:  mattrarick

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
